[package]
name = "ffi_bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
core_crypto = { path = "../kallisto_crypto" }
control_plane = { path = "../kallisto_cluster" }
tokio = { version = "1.0", features = ["full"] }

[build-dependencies]
cxx-build = "1.0"
