sonar.organization=alexanderslokov
sonar.projectKey=AlexanderSlokov_Naughtian-Kallisto

# relative paths to source directories.
sonar.sources=src,cmd,components

# relative paths to test directories.
sonar.tests=tests,benches

# exclude unnecessary files from being scanned
sonar.exclusions=target/**,**/*.md,**/*.json,**/*.toml,coverage_report/**

# Rust coverage reporting (optional, uncomment and configure if using tarpaulin/grcov)
# sonar.rust.coverage.reportPaths=cobertura.xml
