# This CI is failing due to:
#
# ERROR You are running CI analysis while Automatic Analysis is enabled. Please consider disabling one or the other.
#
# TODO: Re-enable this CI after resolving the issue.

# on:
#   # Trigger analysis when pushing to your main branches, and when creating a pull request.
#   push:
#     branches:
#       - main
#       - 1.0.0-alpha
#     tags:
#       - 'v*.*.*'
#       - 'v*.*.*-alpha'
#   workflow_dispatch:
#   pull_request:
#       types: [opened, synchronize, reopened]

# name: SonarCloud
# jobs:
#   sonarqube:
#     runs-on: ubuntu-latest
#     env:
#       BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
#     steps:
#     - uses: actions/checkout@v4
#       with:
#         # Disabling shallow clones is recommended for improving the relevancy of reporting
#         fetch-depth: 0

#     - name: Install dependencies
#       run: |
#         sudo apt-get update && sudo apt-get install -y --no-install-recommends \
#         build-essential ca-certificates cmake curl git ninja-build pkg-config \
#         python3 tar unzip zip

#     - name: Setup vcpkg
#       run: |
#         git clone https://github.com/microsoft/vcpkg.git $RUNNER_TEMP/vcpkg
#         $RUNNER_TEMP/vcpkg/bootstrap-vcpkg.sh -disableMetrics
#         echo "VCPKG_ROOT=$RUNNER_TEMP/vcpkg" >> $GITHUB_ENV

#     - name: Install Build Wrapper
#       uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v4.2.1

#     - name: Run Build Wrapper
#       run: |
#         mkdir -p build && cd build
#         cmake -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" \
#               -DCMAKE_BUILD_TYPE=Release \
#               -DVCPKG_TARGET_TRIPLET=x64-linux-release \
#               -DVCPKG_HOST_TRIPLET=x64-linux-release \
#               -DVCPKG_OVERLAY_TRIPLETS=$GITHUB_WORKSPACE/custom-triplets \
#               ..
#         build-wrapper-linux-x86-64 --out-dir $GITHUB_WORKSPACE/${{ env.BUILD_WRAPPER_OUT_DIR }} make -j$(nproc)

#     - name: SonarQube Scan
#       uses: SonarSource/sonarqube-scan-action@v4.2.1
#       env:
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#       with:
#         args: >
#           --define "sonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"
